services:
  devcontainer:
    image: coolserver
    build: .
    entrypoint: [ "tail", "-f", "/dev/null" ]
    command: 
    network_mode: service:spacetimedb
    volumes:
      - ./cli.toml:/home/spacetime/.config/spacetime/cli.toml
      - .:/app

  spacetimedb:
    image: coolserver
    build: .
    ports:
      - 3000:3000
    command: start
    volumes:
      - ./cli.toml:/home/spacetime/.config/spacetime/cli.toml
      - ./data:/home/spacetime/.local/share/spacetime/data
